namespace BatteryMonitor.Services;

public static class Loc
{
    private static string _lang = "en";

    public static void SetLanguage(string lang) =>
        _lang = _strings.ContainsKey(lang) ? lang : "en";

    public static string Current => _lang;

    public static string Get(string key) =>
        _strings.TryGetValue(_lang, out var d) && d.TryGetValue(key, out var v) ? v : key;

    public static IReadOnlyList<(string Code, string Name)> Languages { get; } =
    [
        ("en", "English"),
        ("de", "Deutsch"),
        ("fr", "Français"),
        ("es", "Español"),
        ("it", "Italiano"),
        ("pt", "Português"),
        ("ro", "Română"),
        ("pl", "Polski"),
        ("nl", "Nederlands"),
        ("tr", "Türkçe"),
        ("ru", "Русский"),
        ("zh", "中文"),
    ];

    /// <summary>
    /// Detects the best matching supported language from the system UI culture.
    /// Falls back to "en" if no match found.
    /// </summary>
    public static string DetectSystemLanguage()
    {
        var lang = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return _strings.ContainsKey(lang) ? lang : "en";
    }

    private static readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["en"] = new()
        {
            ["charging"]        = "Charging",
            ["on_power"]        = "Plugged In",
            ["on_battery"]      = "Battery",
            ["charge_level"]    = "CHARGE",
            ["health"]          = "HEALTH",
            ["charge_rate"]     = "CHARGE RATE",
            ["discharge"]       = "DISCHARGE",
            ["forecast"]        = "FORECAST",
            ["full_in"]         = "FULL IN",
            ["runtime"]         = "RUNTIME",
            ["hours_min"]       = "h:min",
            ["minutes"]         = "minutes",
            ["consumption"]     = "CONSUMPTION",
            ["voltage"]         = "VOLTAGE",
            ["volt"]            = "Volt",
            ["watt"]            = "Watt",
            ["capacity"]        = "CAPACITY",
            ["design_cap"]      = "Design Capacity",
            ["full_cap"]        = "Full Capacity",
            ["remaining"]       = "Remaining",
            ["device"]          = "DEVICE & BATTERY",
            ["model"]           = "Model",
            ["manufacturer"]    = "Manufacturer",
            ["serial"]          = "Serial Number",
            ["updated"]         = "Updated",
            ["show_percent"]    = "Show: Charge %",
            ["show_watt"]       = "Show: Watt",
            ["show_mwh"]        = "Show: mWh",
            ["badge_off"]       = "Badge: Off",
            ["badge_percent"]   = "Badge: Charge %",
            ["badge_watt"]      = "Badge: Watt",
            ["open"]            = "Open",
            ["exit"]            = "Exit",
            ["charging_tt"]     = "Charging",
            ["discharging_tt"]  = "Discharging",
        },
        ["de"] = new()
        {
            ["charging"]        = "Lädt",
            ["on_power"]        = "Am Strom",
            ["on_battery"]      = "Akku",
            ["charge_level"]    = "LADESTAND",
            ["health"]          = "GESUNDHEIT",
            ["charge_rate"]     = "LADELEISTUNG",
            ["discharge"]       = "ENTLADUNG",
            ["forecast"]        = "PROGNOSE",
            ["full_in"]         = "VOLL IN",
            ["runtime"]         = "RESTLAUFZEIT",
            ["hours_min"]       = "Std:Min",
            ["minutes"]         = "Minuten",
            ["consumption"]     = "VERBRAUCH",
            ["voltage"]         = "SPANNUNG",
            ["volt"]            = "Volt",
            ["watt"]            = "Watt",
            ["capacity"]        = "KAPAZITÄT",
            ["design_cap"]      = "Design-Kapazität",
            ["full_cap"]        = "Ist-Kapazität",
            ["remaining"]       = "Verbleibend",
            ["device"]          = "GERÄT & AKKU",
            ["model"]           = "Modell",
            ["manufacturer"]    = "Hersteller",
            ["serial"]          = "Seriennummer",
            ["updated"]         = "Aktualisiert",
            ["show_percent"]    = "Anzeige: Ladestand",
            ["show_watt"]       = "Anzeige: Watt",
            ["show_mwh"]        = "Anzeige: mWh",
            ["badge_off"]       = "Badge: Aus",
            ["badge_percent"]   = "Badge: Ladestand",
            ["badge_watt"]      = "Badge: Watt",
            ["open"]            = "Öffnen",
            ["exit"]            = "Beenden",
            ["charging_tt"]     = "Laden",
            ["discharging_tt"]  = "Entladung",
        },
        ["fr"] = new()
        {
            ["charging"]        = "En charge",
            ["on_power"]        = "Branché",
            ["on_battery"]      = "Batterie",
            ["charge_level"]    = "CHARGE",
            ["health"]          = "SANTÉ",
            ["charge_rate"]     = "PUISSANCE",
            ["discharge"]       = "DÉCHARGE",
            ["forecast"]        = "PRÉVISION",
            ["full_in"]         = "PLEIN DANS",
            ["runtime"]         = "AUTONOMIE",
            ["hours_min"]       = "h:min",
            ["minutes"]         = "minutes",
            ["consumption"]     = "CONSOMMATION",
            ["voltage"]         = "TENSION",
            ["volt"]            = "Volt",
            ["watt"]            = "Watt",
            ["capacity"]        = "CAPACITÉ",
            ["design_cap"]      = "Cap. nominale",
            ["full_cap"]        = "Cap. réelle",
            ["remaining"]       = "Restant",
            ["device"]          = "APPAREIL & BATTERIE",
            ["model"]           = "Modèle",
            ["manufacturer"]    = "Fabricant",
            ["serial"]          = "N° de série",
            ["updated"]         = "Actualisé",
            ["show_percent"]    = "Affich.: Charge %",
            ["show_watt"]       = "Affich.: Watt",
            ["show_mwh"]        = "Affich.: mWh",
            ["badge_off"]       = "Badge: Désact.",
            ["badge_percent"]   = "Badge: Charge %",
            ["badge_watt"]      = "Badge: Watt",
            ["open"]            = "Ouvrir",
            ["exit"]            = "Quitter",
            ["charging_tt"]     = "En charge",
            ["discharging_tt"]  = "Décharge",
        },
        ["es"] = new()
        {
            ["charging"]        = "Cargando",
            ["on_power"]        = "Conectado",
            ["on_battery"]      = "Batería",
            ["charge_level"]    = "CARGA",
            ["health"]          = "SALUD",
            ["charge_rate"]     = "POTENCIA",
            ["discharge"]       = "DESCARGA",
            ["forecast"]        = "PRONÓSTICO",
            ["full_in"]         = "LLENO EN",
            ["runtime"]         = "DURACIÓN",
            ["hours_min"]       = "h:min",
            ["minutes"]         = "minutos",
            ["consumption"]     = "CONSUMO",
            ["voltage"]         = "VOLTAJE",
            ["volt"]            = "Voltios",
            ["watt"]            = "Vatios",
            ["capacity"]        = "CAPACIDAD",
            ["design_cap"]      = "Cap. de diseño",
            ["full_cap"]        = "Cap. real",
            ["remaining"]       = "Restante",
            ["device"]          = "DISPOSITIVO & BATERÍA",
            ["model"]           = "Modelo",
            ["manufacturer"]    = "Fabricante",
            ["serial"]          = "Nº de serie",
            ["updated"]         = "Actualizado",
            ["show_percent"]    = "Mostrar: Carga %",
            ["show_watt"]       = "Mostrar: Watt",
            ["show_mwh"]        = "Mostrar: mWh",
            ["badge_off"]       = "Badge: Desact.",
            ["badge_percent"]   = "Badge: Carga %",
            ["badge_watt"]      = "Badge: Watt",
            ["open"]            = "Abrir",
            ["exit"]            = "Salir",
            ["charging_tt"]     = "Cargando",
            ["discharging_tt"]  = "Descarga",
        },
        ["it"] = new()
        {
            ["charging"]        = "In carica",
            ["on_power"]        = "Collegato",
            ["on_battery"]      = "Batteria",
            ["charge_level"]    = "CARICA",
            ["health"]          = "SALUTE",
            ["charge_rate"]     = "POTENZA",
            ["discharge"]       = "SCARICA",
            ["forecast"]        = "PREVISIONE",
            ["full_in"]         = "PIENO IN",
            ["runtime"]         = "AUTONOMIA",
            ["hours_min"]       = "h:min",
            ["minutes"]         = "minuti",
            ["consumption"]     = "CONSUMO",
            ["voltage"]         = "TENSIONE",
            ["volt"]            = "Volt",
            ["watt"]            = "Watt",
            ["capacity"]        = "CAPACITÀ",
            ["design_cap"]      = "Cap. nominale",
            ["full_cap"]        = "Cap. reale",
            ["remaining"]       = "Rimanente",
            ["device"]          = "DISPOSITIVO & BATTERIA",
            ["manufacturer"]    = "Produttore",
            ["model"]           = "Modello",
            ["serial"]          = "N° di serie",
            ["updated"]         = "Aggiornato",
            ["show_percent"]    = "Mostra: Carica %",
            ["show_watt"]       = "Mostra: Watt",
            ["show_mwh"]        = "Mostra: mWh",
            ["badge_off"]       = "Badge: Off",
            ["badge_percent"]   = "Badge: Carica %",
            ["badge_watt"]      = "Badge: Watt",
            ["open"]            = "Apri",
            ["exit"]            = "Esci",
            ["charging_tt"]     = "In carica",
            ["discharging_tt"]  = "Scarica",
        },
        ["pt"] = new()
        {
            ["charging"]        = "Carregando",
            ["on_power"]        = "Conectado",
            ["on_battery"]      = "Bateria",
            ["charge_level"]    = "CARGA",
            ["health"]          = "SAÚDE",
            ["charge_rate"]     = "POTÊNCIA",
            ["discharge"]       = "DESCARGA",
            ["forecast"]        = "PREVISÃO",
            ["full_in"]         = "CHEIO EM",
            ["runtime"]         = "DURAÇÃO",
            ["hours_min"]       = "h:min",
            ["minutes"]         = "minutos",
            ["consumption"]     = "CONSUMO",
            ["voltage"]         = "TENSÃO",
            ["volt"]            = "Volt",
            ["watt"]            = "Watt",
            ["capacity"]        = "CAPACIDADE",
            ["design_cap"]      = "Cap. nominal",
            ["full_cap"]        = "Cap. real",
            ["remaining"]       = "Restante",
            ["device"]          = "DISPOSITIVO & BATERIA",
            ["model"]           = "Modelo",
            ["manufacturer"]    = "Fabricante",
            ["serial"]          = "Nº de série",
            ["updated"]         = "Atualizado",
            ["show_percent"]    = "Exibir: Carga %",
            ["show_watt"]       = "Exibir: Watt",
            ["show_mwh"]        = "Exibir: mWh",
            ["badge_off"]       = "Badge: Off",
            ["badge_percent"]   = "Badge: Carga %",
            ["badge_watt"]      = "Badge: Watt",
            ["open"]            = "Abrir",
            ["exit"]            = "Sair",
            ["charging_tt"]     = "Carregando",
            ["discharging_tt"]  = "Descarga",
        },
        ["ro"] = new()
        {
            ["charging"]        = "Încărcare",
            ["on_power"]        = "Conectat",
            ["on_battery"]      = "Baterie",
            ["charge_level"]    = "ÎNCĂRCARE",
            ["health"]          = "SĂNĂTATE",
            ["charge_rate"]     = "PUTERE",
            ["discharge"]       = "DESCĂRCARE",
            ["forecast"]        = "PROGNOZĂ",
            ["full_in"]         = "PLIN ÎN",
            ["runtime"]         = "DURATĂ",
            ["hours_min"]       = "h:min",
            ["minutes"]         = "minute",
            ["consumption"]     = "CONSUM",
            ["voltage"]         = "TENSIUNE",
            ["volt"]            = "Volți",
            ["watt"]            = "Watt",
            ["capacity"]        = "CAPACITATE",
            ["design_cap"]      = "Cap. nominală",
            ["full_cap"]        = "Cap. reală",
            ["remaining"]       = "Rămas",
            ["device"]          = "DISPOZITIV & BATERIE",
            ["model"]           = "Model",
            ["manufacturer"]    = "Producător",
            ["serial"]          = "Nr. serie",
            ["updated"]         = "Actualizat",
            ["show_percent"]    = "Afișare: Încărcare %",
            ["show_watt"]       = "Afișare: Watt",
            ["show_mwh"]        = "Afișare: mWh",
            ["badge_off"]       = "Badge: Oprit",
            ["badge_percent"]   = "Badge: Încărcare %",
            ["badge_watt"]      = "Badge: Watt",
            ["open"]            = "Deschide",
            ["exit"]            = "Ieșire",
            ["charging_tt"]     = "Încărcare",
            ["discharging_tt"]  = "Descărcare",
        },
        ["pl"] = new()
        {
            ["charging"]        = "Ładowanie",
            ["on_power"]        = "Podłączony",
            ["on_battery"]      = "Bateria",
            ["charge_level"]    = "POZIOM",
            ["health"]          = "ZDROWIE",
            ["charge_rate"]     = "MOC",
            ["discharge"]       = "ROZŁADOWANIE",
            ["forecast"]        = "PROGNOZA",
            ["full_in"]         = "PEŁNY ZA",
            ["runtime"]         = "CZAS PRACY",
            ["hours_min"]       = "g:min",
            ["minutes"]         = "minut",
            ["consumption"]     = "ZUŻYCIE",
            ["voltage"]         = "NAPIĘCIE",
            ["volt"]            = "Volt",
            ["watt"]            = "Watt",
            ["capacity"]        = "POJEMNOŚĆ",
            ["design_cap"]      = "Poj. projektowa",
            ["full_cap"]        = "Poj. pełna",
            ["remaining"]       = "Pozostało",
            ["device"]          = "URZĄDZENIE & AKUM.",
            ["model"]           = "Model",
            ["manufacturer"]    = "Producent",
            ["serial"]          = "Nr seryjny",
            ["updated"]         = "Zaktualizowano",
            ["show_percent"]    = "Wyświetl: Poziom %",
            ["show_watt"]       = "Wyświetl: Watt",
            ["show_mwh"]        = "Wyświetl: mWh",
            ["badge_off"]       = "Badge: Wył.",
            ["badge_percent"]   = "Badge: Poziom %",
            ["badge_watt"]      = "Badge: Watt",
            ["open"]            = "Otwórz",
            ["exit"]            = "Zakończ",
            ["charging_tt"]     = "Ładowanie",
            ["discharging_tt"]  = "Rozładowanie",
        },
        ["nl"] = new()
        {
            ["charging"]        = "Opladen",
            ["on_power"]        = "Aangesloten",
            ["on_battery"]      = "Batterij",
            ["charge_level"]    = "LADING",
            ["health"]          = "GEZONDHEID",
            ["charge_rate"]     = "VERMOGEN",
            ["discharge"]       = "ONTLADING",
            ["forecast"]        = "PROGNOSE",
            ["full_in"]         = "VOL IN",
            ["runtime"]         = "LOOPTIJD",
            ["hours_min"]       = "u:min",
            ["minutes"]         = "minuten",
            ["consumption"]     = "VERBRUIK",
            ["voltage"]         = "SPANNING",
            ["volt"]            = "Volt",
            ["watt"]            = "Watt",
            ["capacity"]        = "CAPACITEIT",
            ["design_cap"]      = "Ontwerpcap.",
            ["full_cap"]        = "Volledige cap.",
            ["remaining"]       = "Resterend",
            ["device"]          = "APPARAAT & ACCU",
            ["model"]           = "Model",
            ["manufacturer"]    = "Fabrikant",
            ["serial"]          = "Serienummer",
            ["updated"]         = "Bijgewerkt",
            ["show_percent"]    = "Toon: Lading %",
            ["show_watt"]       = "Toon: Watt",
            ["show_mwh"]        = "Toon: mWh",
            ["badge_off"]       = "Badge: Uit",
            ["badge_percent"]   = "Badge: Lading %",
            ["badge_watt"]      = "Badge: Watt",
            ["open"]            = "Openen",
            ["exit"]            = "Afsluiten",
            ["charging_tt"]     = "Opladen",
            ["discharging_tt"]  = "Ontlading",
        },
        ["tr"] = new()
        {
            ["charging"]        = "Şarj",
            ["on_power"]        = "Bağlı",
            ["on_battery"]      = "Pil",
            ["charge_level"]    = "ŞARJ",
            ["health"]          = "SAĞLIK",
            ["charge_rate"]     = "GÜÇ",
            ["discharge"]       = "DEŞARJ",
            ["forecast"]        = "TAHMİN",
            ["full_in"]         = "DOLACAK",
            ["runtime"]         = "SÜRE",
            ["hours_min"]       = "sa:dak",
            ["minutes"]         = "dakika",
            ["consumption"]     = "TÜKETİM",
            ["voltage"]         = "VOLTAJ",
            ["volt"]            = "Volt",
            ["watt"]            = "Watt",
            ["capacity"]        = "KAPASİTE",
            ["design_cap"]      = "Tasarım kap.",
            ["full_cap"]        = "Tam kapasite",
            ["remaining"]       = "Kalan",
            ["device"]          = "CİHAZ & BATARYA",
            ["model"]           = "Model",
            ["manufacturer"]    = "Üretici",
            ["serial"]          = "Seri no",
            ["updated"]         = "Güncellendi",
            ["show_percent"]    = "Göster: Şarj %",
            ["show_watt"]       = "Göster: Watt",
            ["show_mwh"]        = "Göster: mWh",
            ["badge_off"]       = "Rozet: Kapalı",
            ["badge_percent"]   = "Rozet: Şarj %",
            ["badge_watt"]      = "Rozet: Watt",
            ["open"]            = "Aç",
            ["exit"]            = "Çıkış",
            ["charging_tt"]     = "Şarj",
            ["discharging_tt"]  = "Deşarj",
        },
        ["ru"] = new()
        {
            ["charging"]        = "Заряжается",
            ["on_power"]        = "Подключён",
            ["on_battery"]      = "Батарея",
            ["charge_level"]    = "ЗАРЯД",
            ["health"]          = "СОСТОЯНИЕ",
            ["charge_rate"]     = "МОЩНОСТЬ",
            ["discharge"]       = "РАЗРЯД",
            ["forecast"]        = "ПРОГНОЗ",
            ["full_in"]         = "ЗАРЯДИТСЯ",
            ["runtime"]         = "РЕСУРС",
            ["hours_min"]       = "ч:мин",
            ["minutes"]         = "минут",
            ["consumption"]     = "ПОТРЕБЛЕНИЕ",
            ["voltage"]         = "НАПРЯЖЕНИЕ",
            ["volt"]            = "Вольт",
            ["watt"]            = "Ватт",
            ["capacity"]        = "ЁМКОСТЬ",
            ["design_cap"]      = "Проектная",
            ["full_cap"]        = "Реальная",
            ["remaining"]       = "Осталось",
            ["device"]          = "УСТРОЙСТВО",
            ["model"]           = "Модель",
            ["manufacturer"]    = "Производитель",
            ["serial"]          = "Серийный №",
            ["updated"]         = "Обновлено",
            ["show_percent"]    = "Показ: Заряд %",
            ["show_watt"]       = "Показ: Вт",
            ["show_mwh"]        = "Показ: мВтч",
            ["badge_off"]       = "Значок: Откл.",
            ["badge_percent"]   = "Значок: Заряд %",
            ["badge_watt"]      = "Значок: Вт",
            ["open"]            = "Открыть",
            ["exit"]            = "Выход",
            ["charging_tt"]     = "Заряжается",
            ["discharging_tt"]  = "Разряжается",
        },
        ["zh"] = new()
        {
            ["charging"]        = "充电中",
            ["on_power"]        = "已接电",
            ["on_battery"]      = "使用电池",
            ["charge_level"]    = "电量",
            ["health"]          = "健康度",
            ["charge_rate"]     = "充电功率",
            ["discharge"]       = "放电",
            ["forecast"]        = "预测",
            ["full_in"]         = "充满还需",
            ["runtime"]         = "剩余时间",
            ["hours_min"]       = "时:分",
            ["minutes"]         = "分钟",
            ["consumption"]     = "功耗",
            ["voltage"]         = "电压",
            ["volt"]            = "伏特",
            ["watt"]            = "瓦特",
            ["capacity"]        = "容量",
            ["design_cap"]      = "设计容量",
            ["full_cap"]        = "实际容量",
            ["remaining"]       = "剩余",
            ["device"]          = "设备与电池",
            ["model"]           = "型号",
            ["manufacturer"]    = "制造商",
            ["serial"]          = "序列号",
            ["updated"]         = "已更新",
            ["show_percent"]    = "显示: 电量%",
            ["show_watt"]       = "显示: 瓦特",
            ["show_mwh"]        = "显示: 毫瓦时",
            ["badge_off"]       = "徽标: 关",
            ["badge_percent"]   = "徽标: 电量%",
            ["badge_watt"]      = "徽标: 瓦特",
            ["open"]            = "打开",
            ["exit"]            = "退出",
            ["charging_tt"]     = "充电",
            ["discharging_tt"]  = "放电",
        },
    };
}
